Controllers/TerminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using OptiShape.Data;
using OptiShape.Models;

namespace OptiShape.Controllers
{
    [Authorize(Roles = "Administrator, Korisnik, Trener")]
    public class TerminController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public TerminController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            IQueryable<Termin> terminiQuery;

            var appUser = await _userManager.GetUserAsync(User);
            var email = appUser?.Email;

            if (User.IsInRole("Trener"))
            {
                var trener = await _context.Korisnik.FirstOrDefaultAsync(k => k.Email == email);
                if (trener == null)
                    return Forbid();

                terminiQuery = _context.Termin
                    .Include(t => t.Korisnik)
                    .Where(t => t.Korisnik != null && t.Korisnik.IdTrenera == trener.IdKorisnika);

            }
            else if (User.IsInRole("Korisnik"))
            {
                var korisnik = await _context.Korisnik.FirstOrDefaultAsync(k => k.Email == email);
                if (korisnik == null)
                    return Forbid();

                terminiQuery = _context.Termin
                    .Include(t => t.Korisnik)
                    .Where(t => t.IdKorisnika == korisnik.IdKorisnika);
            }
            else
            {
                // Administrator vidi sve termine
                terminiQuery = _context.Termin.Include(t => t.Korisnik);
            }

            return View(await terminiQuery.ToListAsync());
        }


        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            var termin = await _context.Termin.Include(t => t.Korisnik).FirstOrDefaultAsync(m => m.IdTermina == id);

            if (termin == null)
                return NotFound();

            var appUser = await _userManager.GetUserAsync(User);
            var email = appUser?.Email;

            if (User.IsInRole("Trener"))
            {
                var trener = await _context.Korisnik.FirstOrDefaultAsync(k => k.Email == email);
                if (trener == null || termin.Korisnik?.IdTrenera != trener.IdKorisnika)
                    return Forbid();
            }

            return View(termin);
        }

        [Authorize(Roles = "Administrator, Trener")]
        public async Task<IActionResult> Create()
        {

            await PostaviKorisnikeDropdown();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Trener")]
        public async Task<IActionResult> Create([Bind("IdTermina,Datum,IdKorisnika,VrijemeOd")] Termin termin)
        {
            var appUser = await _userManager.GetUserAsync(User);
            var email = appUser?.Email;

            if (User.IsInRole("Trener"))
            {
                var trener = await _context.Korisnik.FirstOrDefaultAsync(k => k.Email == email);
                var korisnik = await _context.Korisnik.FirstOrDefaultAsync(k => k.IdKorisnika == termin.IdKorisnika);

                if (trener == null || korisnik == null || korisnik.IdTrenera != trener.IdKorisnika)
                    return Forbid();
            }

            // Kombinuj datum i vrijeme
            termin.Datum = termin.Datum.Date + termin.VrijemeOd;

            if (ModelState.IsValid)
            {
                _context.Add(termin);
                await _context.SaveChangesAsync();
                TempData["SuccessMessage"] = "Termin je uspješno dodat.";
                return RedirectToAction(nameof(Index));
            }

            if (termin.VrijemeOd == default)
            {
                ModelState.AddModelError("VrijemeOd", "Unesite vrijeme početka.");
            }

            await PostaviKorisnikeDropdown(termin.IdKorisnika);
            return View(termin);
        }


        [Authorize(Roles = "Administrator, Trener")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var termin = await _context.Termin.Include(t => t.Korisnik).FirstOrDefaultAsync(t => t.IdTermina == id);
            if (termin == null)
                return NotFound();

            var appUser = await _userManager.GetUserAsync(User);
            var email = appUser?.Email;

            if (User.IsInRole("Trener"))
            {
                var trener = await _context.Korisnik.FirstOrDefaultAsync(k => k.Email == email);
                if (trener == null || termin.Korisnik?.IdTrenera != trener.IdKorisnika)
                    return Forbid();
            }

            await PostaviKorisnikeDropdown(termin.IdKorisnika);
            return View(termin);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Trener")]
        public async Task<IActionResult> Edit(int id, [Bind("IdTermina,Datum,IdKorisnika")] Termin termin)
        {
            if (id != termin.IdTermina)
                return NotFound();

            var appUser = await _userManager.GetUserAsync(User);
            var email = appUser?.Email;

            if (User.IsInRole("Trener"))
            {
                var trener = await _context.Korisnik.FirstOrDefaultAsync(k => k.Email == email);
                var korisnik = await _context.Korisnik.FirstOrDefaultAsync(k => k.IdKorisnika == termin.IdKorisnika);

                if (trener == null || korisnik == null || korisnik.IdTrenera != trener.IdKorisnika)
                    return Forbid();
            }

            termin.Datum = termin.Datum.Date + termin.VrijemeOd;

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(termin);
                    await _context.SaveChangesAsync();
                    TempData["SuccessMessage"] = "Termin je uspješno ažuriran.";
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TerminExists(termin.IdTermina))
                        return NotFound();
                    else throw;
                }
            }

            await PostaviKorisnikeDropdown(termin.IdKorisnika);
            return View(termin);
        }

        [Authorize(Roles = "Administrator, Trener")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var termin = await _context.Termin.Include(t => t.Korisnik).FirstOrDefaultAsync(m => m.IdTermina == id);
            if (termin == null)
                return NotFound();

            var appUser = await _userManager.GetUserAsync(User);
            var email = appUser?.Email;

            if (User.IsInRole("Trener"))
            {
                var trener = await _context.Korisnik.FirstOrDefaultAsync(k => k.Email == email);
                if (trener == null || termin.Korisnik?.IdTrenera != trener.IdKorisnika)
                    return Forbid();
            }

            return View(termin);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Trener")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var termin = await _context.Termin.Include(t => t.Korisnik).FirstOrDefaultAsync(t => t.IdTermina == id);

            var appUser = await _userManager.GetUserAsync(User);
            var email = appUser?.Email;

            if (termin != null)
            {
                if (User.IsInRole("Trener"))
                {
                    var trener = await _context.Korisnik.FirstOrDefaultAsync(k => k.Email == email);
                    if (trener == null || termin.Korisnik?.IdTrenera != trener.IdKorisnika)
                        return Forbid();
                }

                _context.Termin.Remove(termin);
                TempData["SuccessMessage"] = "Termin je uspješno obrisan.";
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }

        private async Task PostaviKorisnikeDropdown(int? selectedId = null)
        {
            List<SelectListItem> korisnici;
            var appUser = await _userManager.GetUserAsync(User);
            var email = appUser?.Email;

            if (User.IsInRole("Trener"))
            {
                var trener = await _context.Korisnik.FirstOrDefaultAsync(k => k.Email == email);

                if (trener == null)
                {
                    korisnici = new List<SelectListItem>(); // ili baci grešku ako želiš
                }
                else
                {
                    korisnici = await _context.Korisnik
                        .Where(k => k.IdTrenera == trener.IdKorisnika)
                        .Select(k => new SelectListItem
                        {
                            Value = k.IdKorisnika.ToString(),
                            Text = k.Ime + " " + k.Prezime,
                            Selected = k.IdKorisnika == selectedId
                        })
                        .ToListAsync();
                }
            }
            else
            {
                korisnici = await _context.Korisnik

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using OptiShape.Models
@inject SignInManager<ApplicationUser> SignInManager
<!DOCTYPE html> 

<html lang="en">  
<head>  

    <meta charset="utf-8" />  
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />  
    <title>@ViewData["Title"] - OptiShape</title>  
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />  
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />  
    <link rel="stylesheet" href="~/OptiShape.styles.css" asp-append-version="true" />  


    <!-- Font Inter -->
    <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">


    <!-- ANIMACIJE -->
    <style>
        html {
            scroll-behavior: smooth;
        }

        body {
            font-family: 'Inter', sans-serif;
            background-color: #f8fafc;
            margin: 0;
            padding: 0;
            color: #1e293b;
        }

        h1, h2 {
            color: #1e3a8a;
        }

        .fade-in {
            opacity: 0;
            transform: translateY(20px);
            animation: fadeInUp 1.5s ease forwards;
        }

        @@keyframes fadeInUp {
            to

        {
            opacity: 1;
            transform: translateY(0);
        }

        }

        .btn-primary {
            background-color: #2563eb;
            color: white;
            padding: 12px 24px;
            border-radius: 8px;
            text-decoration: none;
            font-weight: 500;
            display: inline-block;
            transition: all 0.3s ease;
        }

            .btn-primary:hover {
                background-color: #1d4ed8;
                transform: scale(1.05);
            }


            /* za nav*/
        .custom-navbar,
        .custom-navbar-alt {
            background-color: white;
            border-bottom: 1px solid #e5e7eb;
            padding: 18px 30px;
            font-family: 'Inter', sans-serif;
            z-index: 1030;
        }

        .navbar-brand {
            font-size: 1.8rem;
            font-weight: 800;
            color: #2563eb !important;
            letter-spacing: -0.5px;
            transition: transform 0.3s ease;
        }

            .navbar-brand:hover {
                transform: scale(1.05);
            }

        .navbar-nav .nav-link {
            font-size: 1.1rem;
            font-weight: 600;
            color: #1e293b;
            padding: 10px 14px;
            border-radius: 6px;
            transition: background-color 0.3s ease, color 0.3s ease, transform 0.2s;
        }

            .navbar-nav .nav-link:hover {
                background-color: #eff6ff;
                color: #2563eb;
                transform: translateY(-1px);
            }

        .navbar-nav.gap-2 > li,
        .navbar-nav.gap-4 > li {
            margin-left: 0.4rem;
            margin-right: 0.4rem;
        }

        .navbar-nav li {
            margin-left: 0.5rem;
            margin-right: 0.5rem;
        }


        /* ZA LOGO */

        .logo-hover {
            transition: transform 0.4s ease, box-shadow 0.4s ease;
        }

            .logo-hover:hover {
                transform: scale(1.08);
                box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2);
            }
    </style>

    @RenderSection("Styles", required: false)
</head>  

<body>  
   
    <header> <!-- NAVBAR -->
        <nav class="navbar navbar-expand-sm @(ViewData["FixedNavbar"] as bool? == true ? "fixed-top custom-navbar shadow-sm" : "custom-navbar-alt")">
            <div class="container-fluid">
                @if (!SignInManager.IsSignedIn(User))
                {
                    <!-- centrirani logo za neulogovane --> 
                    <div class="mx-auto">
                        <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                            <img src="~/images/logo.png" alt="OptiShape" class="logo-hover" style="height: 48px;" />

                        </a>
                    </div>
                }
                else
                {
                    <!-- klasicni tekstualni logo za ulogovane -->
                    <a class="navbar-brand" asp-controller="Home" asp-action="@(SignInManager.IsSignedIn(User) ? "Dashboard" : "Index")">
                        <img src="~/images/logo.png" alt="OptiShape" class="logo-hover" style="height: 48px;" />
                    </a>

                }

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mainNavbar"
                        aria-controls="mainNavbar" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="mainNavbar">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 gap-3">

                        @if (!SignInManager.IsSignedIn(User)) /* UKOLIKO NIJE SIGN INOVAN */
                        {
                            <li class="nav-item">
                                <a class="nav-link" href="/#opis">O aplikaciji</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/#benefiti">Kako započeti</a>
                            </li>
                        }

                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("Administrator")) /* REKSTRIKCIJA NA KORISNICI (SAMO ZA ADMINA) */
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Korisnik" asp-action="Index">Korisnici</a>
                            </li> // samo za admina
                        }

                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="PlanIshraneITreninga" asp-action="Index">
                                    @(User.IsInRole("Korisnik") ? "Moj plan ishrane" : "Planovi ishrane")
                                </a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" asp-controller="StatistikeNapretka" asp-action="Index">Statistike napretka</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Termin" asp-action="Index">Termini</a>
                            </li>
                            @if (User.IsInRole("Administrator"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Placanje" asp-action="Index">Plaćanje</a>
                                </li>
                            }
                        }


                    </ul>

                    <ul class="navbar-nav gap-2">
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>

    </header>

    @{
        var isFixed = ViewData["FixedNavbar"] as bool? == true;

        // Po defaultu fiksiran navbar traži padding
        var mainStyle = isFixed ? "padding-top: 80px;" : "";

        // Ali ne dodaj padding ako korisnik nije logovan (npr. početna stranica ima centrirani logo)
        if (!SignInManager.IsSignedIn(User))
        {
            mainStyle = "";
        }
    }


    <main style="@mainStyle" role="main" class="pb-3">
        @RenderBody()
    </main>

    <footer class="border-top footer text-muted">  
        <div class="container">  
            &copy; 2025 - OptiShape  
        </div>  
    </footer>  
    <script src="~/lib/jquery/dist/jquery.min.js"></script>  
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>  
    <script src="~/js/site.js" asp-append-version="true"></script>  
    @await RenderSectionAsync("Scripts", required: false)  

</body>  
</html>